### ISSUE TITLE
Characters only half visible

### ISSUE THREAD

**Issue by SebastianSchneiderbauer** [DenizCiger/Pugnators#1]
**Describe the bug**
When going to the left or right, the rectangle representing the camera only enlarges until you see half of the body (I guess because the camera system uses the middle of the character as its position). If the camera is placed like this, the character the furthest to the left/right would only be shown half, which doesn't look good.

**To Reproduce**
1. Go to the left/right.
2. Walk until the rectangle representing the camera enlarges.
3. Stop walking.
4. See error.

**Expected behavior**
Rectangle representing the camera should be so big you can see all characters fully.

**Screenshots**
This is what I mean:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/20e313a6-a34d-4af3-b7a2-0c6674f94de2)

How it would look while playing:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/74207d0d-f40a-4aec-a162-386e9cb9c39b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browsers: Microsoft Edge, Chrome, Opera, Opera GX

**Smartphone (please complete the following information):**
- Had not been tested on smartphones for obvious reasons.

**Comment by DenizCiger** [comment]
Currently intended, but planning to change it once the more important bugs are fixed

**Comment by SebastianSchneiderbauer** [comment]
Bug has been fixed.
