### ISSUE TITLE
Camera not shrinking

### ISSUE THREAD

**Issue by SebastianSchneiderbauer** [DenizCiger/Pugnators#2]
**Describe the bug**
When enlarging the Camera (represented by a rectangle), it grows smoothly, but when when it should be shrinking because you move the characters closer together, it stays the same. This causes two issues:
1. Camera does not shrink when its supposed to (to be precise, it doesn´t at all)
2. The camera can get so big, that the blue dot representing the center of the camera moves to the middle of the screen (also causing the browser to use more resources, because of too many calculations i guess).

**To Reproduce**
Steps to reproduce the behavior (only Camera growing to its maximum even though it should be shrinking again):
1. Walk to the left/right of the Platform
2. Jump off the platform/jump into the vertical wall
3. Repeat 2-3 times

**Expected behavior**
Camera should shrink down to its wanted size after you close the gap between your characters.

**Screenshots**
Camera being much bigger then its supposed to be:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/127ef4bd-2462-4b8b-a48b-b3006bff5aa2)

Camera stuck in the middle of the screen after teleporting because of hitting the stage-barriers:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/e880c72b-ff2f-4608-b0ee-e7f5a2f048dc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browsers: Microsoft Edge, Chrome, Opera, Opera GX

**Smartphone (please complete the following information):**
- Had not been tested on smartphones for obvious reasons.

**Additional context**
Also, the camera starts off to small, only  showing very little of the stage, maybe consider adding a minimum-size for the camera:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/de1c1f21-9666-415c-bc3e-ec19a9f2cee5)

**Comment by DenizCiger** [comment]
I have already been aware of the shrinking problem, I haven't implemented the mechanic yet. Working on changing that asap!

**Comment by DenizCiger** [comment]
Also camera starts so small just for testing reasons. Will change when the overall cam-system fully works

**Comment by DenizCiger** [comment]
> 2\. The camera can get so big, that the blue dot representing the center of the camera moves to the middle of the screen (also causing the browser to use more resources, because of too many calculations i guess).

Could you please create a new Issue regarding that, as it doesn't really fit the rest of the topic?

**Comment by SebastianSchneiderbauer** [comment]
> > 2. The camera can get so big, that the blue dot representing the center of the camera moves to the middle of the screen (also causing the browser to use more resources, because of too many calculations i guess).
> 
> Could you please create a new Issue regarding that, as it doesn't really fit the rest of the topic?

no

**Comment by SebastianSchneiderbauer** [comment]
Camera bug got fixed
