### ISSUE TITLE
Character icons not placed correctly

### ISSUE THREAD

**Issue by SebastianSchneiderbauer** [DenizCiger/Pugnators#3]
**Describe the bug**
2 of the 4 character icons are not displayed correctly and are placed 1 pixel to the right. There´s also a small issue with the pixel art of the textures behind the icon and stats of your character.

**Screenshots**
Leonding Chan not being placed correctly:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/bcd399dd-a2e7-46c4-881e-8ab6bf816eca)

Troller not being placed correctly:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/eb8d9958-1546-4043-906b-4ea0cecbfc25)

Small issue with the pixel art of the "icon-background":
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/3cea4133-de1f-48ad-897f-aef0cc6db670)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browsers: Microsoft Edge, Chrome, Opera, Opera GX

**Smartphone (please complete the following information):**
- Had not been tested on smartphones since this isn´t supposed to be opened on mobile.

**Comment by DenizCiger** [comment]
> Small issue with the pixel art of the "icon-background":
> ![image](https://private-user-images.githubusercontent.com/146381631/303753354-3cea4133-de1f-48ad-897f-aef0cc6db670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTA4OTksIm5iZiI6MTcwNzUxMDU5OSwicGF0aCI6Ii8xNDYzODE2MzEvMzAzNzUzMzU0LTNjZWE0MTMzLWRlMWYtNDhhZC04OTdmLWFlZjBjYzZkYjY3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQyMDI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmRlZjU0ZTM5ZGI4MmVmMWQzMTZiNzY3MzgyMDNkMmY2ZGI0YmUwMzNhNzA5NGJmNDIwYjM0NjAxNDNlNmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TgFbarUN98frQxqnZBi4H_tJNKZPmoujtHbgxdvrL6A)

Could you go more in-depth about the problem with the icon-background?

**Comment by DenizCiger** [comment]
> **Describe the bug**
> 2 of the 4 character icons are not displayed correctly and are placed 1 pixel to the right. There´s also a small issue with the pixel art of the textures behind the icon and stats of your character.

I've been aware of this for quite some time, but I'm planning to fix UI stuff once most of the main game mechanics are functional

**Comment by SebastianSchneiderbauer** [comment]
> > Small issue with the pixel art of the "icon-background":
> > ![image](https://private-user-images.githubusercontent.com/146381631/303753354-3cea4133-de1f-48ad-897f-aef0cc6db670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTA4OTksIm5iZiI6MTcwNzUxMDU5OSwicGF0aCI6Ii8xNDYzODE2MzEvMzAzNzUzMzU0LTNjZWE0MTMzLWRlMWYtNDhhZC04OTdmLWFlZjBjYzZkYjY3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQyMDI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmRlZjU0ZTM5ZGI4MmVmMWQzMTZiNzY3MzgyMDNkMmY2ZGI0YmUwMzNhNzA5NGJmNDIwYjM0NjAxNDNlNmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TgFbarUN98frQxqnZBi4H_tJNKZPmoujtHbgxdvrL6A)
> 
> Could you go more in-depth about the problem with the icon-background?

The sprite can be divided into 2 parts, the square where the player icon is placed and 2 rectangles for Playername and knockback. Where those two parts connect, 3 pixels were removed on the top, while only 1 was removed at the bottom

**Comment by SebastianSchneiderbauer** [comment]
The problem was solved by tweaking some values in the game.css file, issue will be closed.
