### ISSUE TITLE
Wallsliding doesn't refill jumps

### ISSUE THREAD

**Issue by SebastianSchneiderbauer** [DenizCiger/Pugnators#4]
**Describe the bug**
When jumping off a wall, you cant jump anymore until you reach the floor. Even though you haven't jumped before. 

**To Reproduce**
1. Walk off the platform
2. While falling, turn around so you are wall-sliding on the side of the platform
3. Press the jump button once, launching you up the platform's side
4. Now press in any direction while still jumping (jumping into the void or back onto the platform doesn't make a difference)
5. While in air, you cant jump without touching the ground first, even though you theoretically still have one jump

**Expected behavior**
Character should be able to jump once more after launching off the platform's side

**Additional context**
Maybe this is a feature, but it feels unintuitive. It may also be because it registers 2 jump inputs before launching you up, since i had one try where the second jump worked as intended. However, in most of my tries, it did not work.

**Comment by DenizCiger** [comment]
This issue has been fixed in the new online-multiplayer version that is currently being worked on
