### ISSUE TITLE
player is always rendered above the platform

### ISSUE THREAD

**Issue by SebastianSchneiderbauer** [DenizCiger/Pugnators#5]
**Describe the bug**
When jumping under the platform, the player sprite is till rendered above the mushroom-platform, even though it shoull be shown beneath

**To Reproduce**
1. Simply jump under the platform and jump up again using your doublejump

**Expected behavior**
Playersprites should be rendered beneath the mushroom platform if the player is going underneath it

**Screenshots**
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/7573e472-b80d-47a0-b596-b544d0ce5c39)

**Potential Solutions**
I can think of 2 Solutions:
1. Only render the player on top of the platform if he is above this hight (indicated by the purple line)
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/d4725d09-c79d-43d1-a3b0-46016de83e91)
2. Split the platform into two parts:
The part that is rendered below the player:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/2a9ca48a-80b1-4cdd-887b-3190b4a49cc6)
And the part that is rendered on top of the player:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/d8b791a3-b5eb-4de9-9651-01585b03ce7c)

**Comment by SebastianSchneiderbauer** [comment]
The second solution would also be handy because it could be used to create better maps in the future

**Comment by DenizCiger** [comment]
3d platforms can be tricky when 2d players interact with it. If someone could find out how other games handle this, that would really help me to work on a fix!

**Comment by SebastianSchneiderbauer** [comment]
It seems like most games i could find simply don't use objects rendered on top of the player, since it could make it hard to plan your next move if you don't see where you are. This also means that they handle maps like this:

Dream Land (Super Smash Bros)
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/914625c6-220b-4704-83ef-9b8891f75b2e)
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/47723536-a88e-4181-b12e-5bdcdee98baf)

The player is not able to enter the red zone (sometimes simpler or more complex, depending on the game), this technique is also used in other maps and games.

Brawlhaven (Brawlhalla)
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/ccf8a0e4-a44a-4f55-bdb5-0636c590db65)

is using the same technique, but combining it with nearly 2d rectangle-platforms that are using a good texture file to appear 3d, which make it much easier to have collisions while still having a 3d-looking-stage.

The only use of layers being rendered on top of the player I found is in platforms like this:
 WarioWare, inc. (Super Smash Flash 2 Demo)
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/35e92623-315e-4ba9-857c-1eb8fe8a666e)

Here 2 sprite are used to make the platforms the player can jump on and fall threw.
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/224cb1c2-eb4f-4413-820e-08e075f56958)

However, this is not the case in every game, for example Brawlhalla always renders the player on top of these platforms:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/b49bdb44-95a8-4fd7-bd13-283b3c1ce0ea)

So to answer your question, most games avoid 3d-looking-maps or simply treat them as a 2d sprite.

**Comment by DenizCiger** [comment]
Great research! That means, that we should probably change up the current sprite of the map to be 2d or more cubic shaped, as having polygonal hitboxes would not only take some time to code, but also to calculate everytime.

**Comment by DenizCiger** [comment]
> 2. Split the platform into two parts:

That would also be a great solution, but if think that the red part of the mushroom should be split into top and bottom like this:

![image](https://github.com/DenizCiger/Pugnators/assets/62888457/9662907d-3c61-4977-8928-63be07e9a7d8)

**Comment by SebastianS-HTL** [comment]
> > 2. Split the platform into two parts:
> 
> That would also be a great solution, but if think that the red part of the mushroom should be split into top and bottom like this:
> 
> ![image](https://private-user-images.githubusercontent.com/62888457/309543145-9662907d-3c61-4977-8928-63be07e9a7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjI2OTgsIm5iZiI6MTcwOTQ2MjM5OCwicGF0aCI6Ii82Mjg4ODQ1Ny8zMDk1NDMxNDUtOTY2MjkwN2QtM2M2MS00OTc3LTg5MjgtNjNiZTA3ZTlhN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDEwMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjQxM2Y0MTRlY2IxOTcxZjU4MTFlZTUxYzJjOGU5MDhmOGY3YTFhNDJlODI3M2QxZmI5NTVjNGI1ZWQxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfHbq45VtzGZIAj8vK_zo3NDRO8RpRsuGGhpa_GCecg)

should I do it rn and if what should i call the 2 files?
