### ISSUE TITLE
play.html appears "zoomed out" when being opened in chrome

### ISSUE THREAD

**Issue by SebastianSchneiderbauer** [DenizCiger/Pugnators#6]
**Describe the bug**
Until now, we have only tested play.html in edge and Opera GX, but i tried starting it in Chrome and came across a small error. When the file is opened in chrome, it looks "zoomed out" and only  "looks normal" when being scaled to 150% (tested on current version of chrome)

how it looks in microsoft edge:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/19c87c6d-f026-43f9-88ad-ab8f1a33bed6)

how it looks in chrome:
![image](https://github.com/DenizCiger/Pugnators/assets/146381631/0a8acd9d-aec5-44ed-9564-83397e53fd61)

**Comment by DenizCiger** [comment]
Try navigating to ```chrome://flags``` and click the button in the upper right hand corner labeled ```Reset All To Default```. I don't think that's the website's fault.
